### ISSUE TITLE
[Custom Elements] V1 polyfill innerHTML broken when used inside constructor, causes infinite recursion crash

### ISSUE THREAD

**Issue by TimvdLippe** [webcomponents/polyfills#109]
_From @Jeff17Robbins on September 8, 2017 22:29_

Using the [V1 polyfill](https://github.com/webcomponents/webcomponentsjs), I created [an ES5 babel transpilation of the `<x-product>` example](https://jeff17robbins.github.io/V1-Issues/inert_polyfill_innerHTML.html) found at [MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements).  

The custom element's constructor essentially wraps an `<img>` element.  The salient code is:

```
                var img = document.createElement('img');
                img.alt = _this.getAttribute('data-name');
                img.src = _this.getAttribute('data-img');
                img.width = '150';
                img.height = '150';
                img.className = 'product-img';
                //_this.appendChild(img);  // this works
                _this.innerHTML = img.outerHTML;  // this creates a recursive loop in the polyfill
```

As shown, if instead of appending the `<img>`  I instead assign to `.innerHTML`, the assignment causes a loop back into constructing `<x-product>`.  And so on until stack crash.

This crash reproduces on Chrome, MS Edge, IE11, and Firefox.

I don't understand why the polyfill's `.innerHTML` apparently re-triggers the upgrade process on the element, but if you are encapsulating a 3rd party library and need to construct something in your constructor, obviously you can't control if the 3rd party chooses to use `.innerHTML`.  

Also, [a native version of this same page](https://jeff17robbins.github.io/V1-Issues/inert_native_innerHTML.html) does not crash.  

_Copied from original issue: webcomponents/webcomponentsjs#841_

**Comment by azakus** [comment]
Seems like a combination of #106 and #138
