### ISSUE TITLE
[Custom Elements] Prevent double-installation of es5 shim

### ISSUE THREAD

**Issue by dfreedm** [webcomponents/polyfills#121]
Figure out bikeshedding from https://github.com/webcomponents/custom-elements/pull/194

**Comment by azakus** [comment]
@rictic @bicknellr

**Comment by aomarks** [comment]
@rictic do you know if this is still an issue (see https://github.com/webcomponents/custom-elements/pull/194 for more context).

**Comment by rictic** [comment]
It's no longer an issue inside google, and I don't think it's a problem outside google either, so yeah I suspect this is solved
