### ISSUE TITLE
custom properties on IE out of the box?

### ISSUE THREAD

**Issue by benoitjchevalier** [webcomponents/polyfills#14]
I use to work with Polymer a lot and had no problems using CSS custom properties on IE, including dynamically changing a theme, everything was working fine through the `<custom-style>` tags.

I am now building a set of Angular Elements (the Angular wrapper that create custom-elements around an angular component). I'm having a hard time getting the custom properties to work on IE 11, my assumption was that I would "just need" to import the complete webcomponentsjs polyfill and be able to use those properties in the components css but that doesn't seem to be the case.

Has anyone a quick answer on whether my assumption of "stuff should just work" is true or if I'll need to write some special boilerplate code for angular elements (I'm starting to think that maybe the `custom-style` tags and Polymer were doing work behind the scene on top of the polyfill to ensure that everything worked on IE)?

**Comment by azakus** [comment]
This is probably the same issue as #55.
