### ISSUE TITLE
Values Returned from querySelectorAll Don't Support the item method

### ISSUE THREAD

**Issue by alienriver49** [webcomponents/polyfills#178]
### Description
Calling the `item` method on the value returned from `querySelectorAll` results in an error: `TypeError: Object doesn't support property or method 'item'`

#### Live Demo
https://jsbin.com/jofafotubi/edit?html,console,output

#### Steps to Reproduce
1. Store the results of `querySelectorAll` in a variable
2. Call the `item` method on that variable

#### Expected Results
The `item` method is supported on the result from `querySelectorAll`.

#### Actual Results
An error is thrown when attempting to use the `item` method on the result from `querySelectorAll`.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [x] IE 11

**Comment by caridy** [comment]
ref implementation used by lwc's synthetic shadow dom: https://github.com/salesforce/lwc/blob/master/packages/%40lwc/synthetic-shadow/src/shared/static-node-list.ts

it covers a lot of ground, but still it is very hard to create something that is fast and can passed WPT.
