### ISSUE TITLE
Feature request: Ponyfill option

### ISSUE THREAD

**Issue by askbeka** [webcomponents/polyfills#194]
### Description

It will be nice to have ponyfill version of this polyfills so that, globals are not affected.

- This is usefull since singe page can contain different verions of polyfill and still function.
- In combination with babel, and anlogous plugin to [transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime), but with webcomponents helpers, can result in better bundle size,  bause of on demand polyfilling.

**Comment by bicknellr** [comment]
Generally, the intent of the polyfills is to modify the environment's globals to make it appear that certain features are supported, even though they aren't part of the environment's default API surface. Also, having multiple versions of a polyfill for a single feature on one page isn't a something we intend to support: the polyfills usually need to know about all users of their particular feature to successfully implement that feature (for example, style scoping and custom element reactions) and layering more than one would mean neither would work as expected.

I'm going to close this for now, but maybe you have a specific use case in mind that I'm not accounting for? If so, feel free to leave a comment and we can reopen.
