### ISSUE TITLE
Style rules still affects the shadow DOM

### ISSUE THREAD

**Issue by wini3d** [webcomponents/polyfills#202]
Style rules affecting the shadow DOM on older Chrome/Firefox versions

#### Live Demo
Trying a simple example here.
https://blog.logrocket.com/understanding-shadow-dom-v1-fa9b81ebe3ac/
https://jsbin.com/yoconasubo/edit?html,output

#### Steps to Reproduce
```
<div><p>Light DOM</p></div>
<div id="host"></div>

<script>
  const elem = document.querySelector('#host');
  const shadowRoot = elem.attachShadow({mode: 'open'});
  shadowRoot.innerHTML = `
    <p>Shadow DOM</p>
    <style>p {color: red}</style>`;

</script>
```

#### Expected Results
![](https://i1.wp.com/storage.googleapis.com/blog-images-backup/1*suNI_ZRw7DTKw4qVglba2A.png?resize=699%2C256&ssl=1)

#### Actual Results
Both p tags are red in color

### Browsers Affected

- [x] Chrome
- [x] Firefox

### Versions
- webcomponents: v2.0.0

**Comment by aomarks** [comment]
ShadyCSS is not a transparent polyfill, it requires you to make some API calls. Also, it only supports the use of shadow roots on custom elements, not on built-in elements like the <div> in your example, and it requires the use of a <template> element.

See https://github.com/webcomponents/polyfills/tree/master/packages/shadycss#usage for documentation on how to integrate ShadyCSS with your own custom element. (Note if you are using LitElement or PolymerElement, this is handled automatically).

It is a valid criticism that this use case is not supported, but support for this pattern is not practical for us to implement at the moment, given the limited demand and resources.
