### ISSUE TITLE
[ShadyDOM] doesn't register data-* attributes changed through elem.dataset

### ISSUE THREAD

**Issue by HeavenVolkoff** [webcomponents/polyfills#207]
### Description
ShadyDOM doesn't call `elem.attributeChangedCallback` on observed `data-*` attributes that are changed through `elem.dataset`. Browsers that support shadow dom natively register the changes made through `elem.dataset` and call `elem.attributeChangedCallback`.

#### Live Demo
https://jsbin.com/huyujujepu/edit?html,console,output

#### Steps to Reproduce
1. Create `my-element` class
2. Define a `data-attr` in `my-element`'s observedAttributes
2. Append `my-element` to document.body
4. Change `my-element`'s `data-attr` attribute with `document.querySelector("my-element").dataset.attr = "value"`

#### Expected Results
`elem.attributeChangedCallback` get's called with changed value

#### Actual Results
Nothing happens

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari (Not tested)
- [ ] IE 11 (Not tested)

**Comment by aomarks** [comment]
This is true, the custom-elements polyfill does not patch the `dataset` property so it cannot observe changes to it. But it's impractical support it, so unfortunately we won't be able to fix this.

Supporting `dataset` requires being able to observe all of the properties that are set on the `dataset` object, and the Proxy API needed to do that is also not supported by IE11. The https://github.com/GoogleChrome/proxy-polyfill polyfill is very limited in that it required knowing the properties that could be set upfront, and I don't believe there's a better way.

I've added this to our list of known limitations here: https://github.com/webcomponents/polyfills/pull/364
