### ISSUE TITLE
IE11 support: Modules

### ISSUE THREAD

**Issue by cekvenich** [webcomponents/polyfills#210]
IE11 is listed as supported (as it has sufficient market share and is needed for my project).

But is says: 'Given that ES modules have shipped in most browsers, the expectation is that web components code will be loaded via ES modules.'

Can I Use says modules are not supported on IE11. 

Can this be clarified: Modules with IE11, or...

**Comment by web-padawan** [comment]
General convention is to provide ES module bundle for evergreen browsers with ES5 `nomodule` version for IE11.

You can use tools like [webpack-babel-multi-target-plugin](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin) to do it.

**Comment by cekvenich** [comment]
@web-padawan So is there a docs or example of ie 11 support?

**Comment by aomarks** [comment]
These polyfills are not distributed as modules, you can load the published scripts directly. In general, if you're authoring in ES modules, then for compatibility with IE11 you'll need to use a tool like rollup or webpack to generate a classic-style script bundle. https://open-wc.org/guide/ is a good starting point for general info on web component authoring, tooling, etc. that will cover this area.
