### ISSUE TITLE
shadyCSS v1.9.2 doesn't work in IE11

### ISSUE THREAD

**Issue by dtanp** [webcomponents/polyfills#211]
### Description
I've upgraded to latest polyfills (v2.3) and `<custom-style>` stop working in IE11. I have tried to rollback just shadyCSS to v1.9.1 and it fixed the issue.

#### Steps to Reproduce
Use `<custom-style>` to wrap CSS Variables. It should make the CSS Variables works in IE11 but it doesn't work anymore with shadyCSS v1.9.2

#### Expected Results
Any CSS Variables wrapped inside `<custom-style>` should be applied correctly in IE11.

#### Actual Results
The CSS Variables doesn't apply in IE11. Chrome is working fine. No error in console.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x ] IE 11

**Comment by aomarks** [comment]
Could you link a full repro example of this problem using a site like glitch.com?

**Comment by dtanp** [comment]
@aomarks I can close this issue. Things on our side has changed a lot since last year so now we don't have the issue anymore.

For people who may have the issue with ShadyCSS, we found that there is slightly issue with ShadyCSS if you pass style that contains empty content, for example.

```
<style scope="body"></style>
```

Our solution is to remove those empty content before passing to the ShadyCSS.
