### ISSUE TITLE
ShadyCSS polyfill not properly handling CSS in Edge

### ISSUE THREAD

**Issue by elias6** [webcomponents/polyfills#213]
I am building a widget for third-party websites, using shadow DOM to prevent their CSS from interfering with ours. I am using the [ShadyDOM](https://github.com/webcomponents/polyfills/tree/master/packages/shadydom) and [ShadyCSS](https://github.com/webcomponents/polyfills/tree/master/packages/shadycss) polyfills to make it work in Edge and IE, but it is not transforming the CSS for the shadow DOM as I would expect.

Example (a runnable example can be found at https://stackoverflow.com/questions/58174537/shadycss-polyfill-not-properly-handling-css-in-edge):

```html
<!DOCTYPE html>
<html>
	<head>
		<title>Shadow DOM test</title>
	</head>
	<body>
		<div id="container">container is here</div>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/2.3.0/webcomponents-bundle.js"></script>
		<script>
			const shadow = document.getElementById("container").attachShadow({ mode: "open" });
			const style = document.createElement("style");
			style.innerHTML = `
				:host .stuff {
					background: #ff00ff;
				}
			`;
			shadow.appendChild(style);
			const div = document.createElement("div");
			div.classList.add("stuff");
			div.innerHTML = "stuff inside shadow dom";
			shadow.appendChild(div);
		</script>
	</body>
</html>
```

In Chrome (which supports shadow DOM natively), the `stuff` div has a pink background, as I would expect. But in Edge (which does not support shadow DOM natively), I see the "stuff inside shadow dom" text (meaning my script ran and the ShadyDOM functions worked), but I don't see the pink background.

**Why is this happening?** I am attaching a shadow root to a plain old div, instead of using custom elements as the example in the ShadyCSS README does, but does that matter? If so, **how can I make this work?** I am working on a big, existing app, and not wanting to make too many changes at once, so I would strongly prefer to use the standard HTML elements I am already using (`div`s, `button`s, etc.) instead of coming up with my own elements or templates.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [x] IE 11

**Comment by aomarks** [comment]
ShadyCSS is not a transparent polyfill, it requires you to make some API calls. Also, it only supports the use of shadow roots on custom elements, not on built-in elements like the `<div>` in your example, and it requires the use of a `<template>` element.

See https://github.com/webcomponents/polyfills/tree/master/packages/shadycss#usage for documentation on how to integrate ShadyCSS with your own custom element. (Note if you are using LitElement or PolymerElement, this is handled automatically).

It is a valid criticism that this use case is not supported, but support for this pattern is not practical for us to implement at the moment, given the limited demand and resources.
