### ISSUE TITLE
IE11 performance question

### ISSUE THREAD

**Issue by sschottler** [webcomponents/polyfills#215]
### Description

I've read that ["The polyfill gets slower as the size of your page and number of custom element definitions increases."](https://github.com/webcomponents/polyfills/tree/master/packages/custom-elements#customelementspolyfillwrapflushcallback) I wrote a simple test for IE11 to understand this better and have questions (below) about whether anything can be done to improve performance.

#### Live Demo

https://jsbin.com/nebitij/3/edit?html,console,output

```html
<!DOCTYPE html>
<html>
  <head>
    <!-- uncomment/comment this: -->
    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.3.0/webcomponents-loader.js"></script>
  </head>
  <body>
    <label for="nodes"># of nodes to add:</label>
    <input type="text" name="nodes" id="nodes" value="10000" />
    <button onClick="addNodes()">Add Nodes</button>

    <div id="output"></div>

    <script>
      function addNodes() {
        var start = performance.now();

        var output = document.getElementById("output");

        var numberOfNodes = Number(document.getElementById("nodes").value);

        for (var i = 0; i < numberOfNodes; i++) {
          var div = document.createElement("div");
          div.innerHTML = "test";

          output.appendChild(div);
        }

        var end = performance.now();
        var timeInMilliseconds = end - start;
        var seconds = timeInMilliseconds / 1000;

        alert("Nodes added: " + seconds.toFixed(2) + " seconds");
      }
    </script>
  </body>
</html>

```
#### Steps to Reproduce

1. Run the page above in IE11
2. Click "Add Nodes." 10,000 test divs will get added and an alert will popup showing how many seconds it takes to complete
3. Comment out the polyfill loader and reload page
4. Click "Add Nodes" again and wait for alert message.
5. Observe the time difference with polyfill and without

#### Actual Results

Adding the 10,000 test divs takes less than 1 second without the polyfill for me on my macbook pro (running IE11 on virtualbox). It takes around 6 seconds with the polyfill. As I add more nodes, clicking the button and adding the same # of additional nodes takes longer and longer as the total # of page nodes grows.

#### Expected Results

Even without custom elements in my test, I expected all the wrapped/patched dom api calls to add some overhead to all dom calls and be slow in IE11, but I have questions:

#### Questions

1) Which part of the polyfill is contributing most to the performance impact? Would it be significantly faster without ShadyCSS/ShadyDOM if we only wrote custom elements that didn’t use shadow dom? If so, is there an easy way to make the loader not load ShadyCSS/ShadyDOM so I still get all the feature detection logic for other polyfills? I saw there used to be a "webcomponents-lite" bundle that seemed to not have shadow dom, but it's unclear if that's for v0 or v1

2) Is there any way to "scope" this performance hit to just a specific part of the page that uses custom elements/shadow dom/templates/etc. and not affect other dom calls that don't need custom elements/shadow dom/etc.? I suspect not since you have to wrap/patch all these global dom apis, but I am doing my due diligence so we can determine if this is viable to use at work in a production website.

#### Background

We recently used the polyfill bundle in a production website and had some significant performance problems in IE11. The particular page was rather complex (5700 dom nodes) and started taking over 45 seconds to load on my macbook pro on IE11 (it’s a SPA page that gets built up client side after the polyfill has been loaded). Removing the polyfill made it go back to normal. 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [x] IE 11

**Comment by AndyOGo** [comment]
@sschottler 
I observed similar performance issues with this polyfill in IE11 and searched for other solution.

Literally the best state of the art polyfills I found are and I can recommend them practical experience:
- [`document-register-element`](https://github.com/WebReflection/document-register-element) supports CE *v1* despites it's name
- [`@ungap/custom-elements-builtin`](https://github.com/ungap/custom-elements-builtin)
- [`attachshadow`](https://github.com/WebReflection/attachshadow)

**Comment by sschottler** [comment]
Update for others who are curious:

I used the IE11 profiler to figure out which polyfill was causing the most overhead in the patched calls. Initially, I just saw "tz, aq" minified gibberish function calls all coming from the bundle, which made it hard to understand what polyfill inside the bundle (custom elements? Shady dom? ShadyCSS..?) was causing the most overhead. So I cloned the repo and built each polyfill in debug mode (unminified) and transpiled to es5 with babel, then loaded the unminified/es5 polyfills in the same order that they're ultimately imported in the bundle and ran the profiler again. ShadyDOM is indeed causing the most overhead. Specifically, the insertBefore patched node call, which all dom mutations forward to (such as appendChild). 

![shadydomprofiler](https://user-images.githubusercontent.com/36276352/67902230-2132ce80-fb3f-11e9-8f89-619a451b774c.png)

Interestingly, Shady DOM runs slower and slower as more nodes are added to the page. If just custom elements is loaded without shady dom, adding the same # of nodes each time takes roughly the same amount of time, but Shady DOM seems to have to do much more work as the page grows.

**Comment by web-padawan** [comment]
@sorvell would you have time to investigate this? These IE11 performance issues are quite annoying.

**Comment by sschottler** [comment]
Interesting. Yeah, this was not in the docs so I did not know to try it. I will explore. Thanks for the tip!

**Comment by sschottler** [comment]
Tried it:

http://engineering.rallyhealth.com/polyfill-tests/add-nodes-test/nopatch.html

And yes, the shadydom patch overhead is gone and it only has the overhead of the patches from custom elements now on IE11. You can easily compare with the nopolyfills version:

http://engineering.rallyhealth.com/polyfill-tests/add-nodes-test/nopolyfills.html

For me, CE patches were taking about twice as long on IE11 running on virtualbox on macbook pro (1.5 seconds vs 0.8 seconds without polyfills), but your results will vary depending on setup.

Also, I do not see a script with just the "pf" platform polyfills (like Object.assign, Promise, etc.) in there. For now, I'm loading a large core-js script, but it would be better to only load the specific platform polyfills required by the sd and ce scripts.

When you guys restructure scripts to deal with the ordering issue, it might be helpful to include a "pf" script by itself somewhere. Thanks!

**Comment by sschottler** [comment]
Also, I have an example custom element with `noPatch="on-demand"` _partly_ working. It requires the explicit `ShadyDOM.wrap` calls mentioned:

http://engineering.rallyhealth.com/polyfill-tests/example-elements/ce-sd-nopatch.html

However, the `<slot>` renders the distributed nodes incorrectly - above the `h1` instead of under. I tried wrapping the template, but it didn't work. 

```javascript
const template = document.createElement("template");

template.innerHTML = `
<style>
  :host {
    background: red;
    display: block;
    padding: 8px;
  }

  h1 {
    color: white;
  }
</style>
<h1>Custom Element With Shadow DOM</h1>
<div>
  <slot></slot>
</div>
`;

// ShadyCSS (scoping-shim) requires explicit call:
window.ShadyCSS &&
  ShadyCSS.prepareTemplate(template, "custom-element-with-shadow-dom");

class CustomElementWithShadowDOM extends HTMLElement {
  connectedCallback() {
    // wrap check necessary for modern browsers that won't load polyfill:
    const wrap =
      window.ShadyDOM && ShadyDOM.noPatch === "on-demand" && ShadyDOM.wrap;
    const self = wrap ? ShadyDOM.wrap(this) : this;

    // ShadyCSS (scoping-shim) requires explicit call:
    window.ShadyCSS && ShadyCSS.styleElement(self);

    if (!self.shadowRoot) {
      self.attachShadow({ mode: "open" });
      // probably need to ShadyDOM.wrap template node or cloned node,
      // but neither seemed to work:
      const content = template.content.cloneNode(true);
      self.shadowRoot.appendChild(content);
    }
  }
}

customElements.define(
  "custom-element-with-shadow-dom",
  CustomElementWithShadowDOM
);
```

**Comment by sorvell** [comment]
Thanks for posting this test case. We've found what looks like a very significant issue that's easily addressed via #225.

**Comment by sorvell** [comment]
With you `on-demand` example, I think the issue is something with `core-js`. I tried a similar setup with the `webcomponents-platform` and the promise polyfill in the webcomponents repo and it worked ok. Also, for what it's worth you do not need to use `ShadyDOM.wrap` in this example since `attachShadow` is pre-patched and the rest is done on-demand.

**Comment by sschottler** [comment]
Cool - glad I could help. I made the isShadyRoot change from #225 locally and rebuilt shadydom and tried it with the 10,000 div test:

1. Goes from ~6.6 seconds to ~4.2 seconds or so for first click. So certainly faster, but if I remove shady dom altogether, it's around ~1.8 seconds with just the ce patches. I'm running the debug mode scripts on IE11 in a vm so those #s would all be lower with production build scripts running IE11 directly, but I would expect the relative differences to be similar.

2. If I click the button repeatedly, the time to add the same # of nodes each time does not increase O(n) anymore. Stays roughly constant, so that's way better, especially for a 1 line fix!

Should I open a separate issue for my [previous comment](https://github.com/webcomponents/polyfills/issues/215#issuecomment-548599397)?

**Comment by sschottler** [comment]
> With you `on-demand` example, I think the issue is something with `core-js`. I tried a similar setup with the `webcomponents-platform` and the promise polyfill in the webcomponents repo and it worked ok. Also, for what it's worth you do not need to use `ShadyDOM.wrap` in this example since `attachShadow` is pre-patched and the rest is done on-demand.

I originally tried it without `ShadyDOM.wrap` and it didn't render properly so I added it. However, that could be due to using the core-js for platform polyfills as well. Is this the `webcomponents-platform` you reference? 

https://github.com/webcomponents/webcomponents-platform

Looks like it has all the stuff referenced by "pf" part of the bundle scripts. I'll give it a shot. Thanks

**Comment by sschottler** [comment]
Using the webcomponents-platform and promise polyfills instead of core-js fixed the slot issue:

http://engineering.rallyhealth.com/polyfill-tests/example-elements/ce-sd-nopatch.html

However, I do need to explicitly call `ShadyDOM.wrap` inside the custom element to make it work. Otherwise, I get an error about `attachShadow` missing:

<img width="1097" alt="Screen Shot 2019-10-31 at 10 06 29 PM" src="https://user-images.githubusercontent.com/36276352/67997764-fa9e9180-fc2b-11e9-91f7-89a194968c21.png">

**Comment by sorvell** [comment]
For what it's worth, I was unable to reproduce the problem with the test on Internet Explorer 11 so perhaps it's a sub-version issue. I did reproduce the bad performance on Edge (16-18) and there the performance improvement for the fix in the linked PR was really big (test went from ~4.5s to ~.6s).

**Comment by sorvell** [comment]
@sschottler For your test of `noPatch = on-demand`, it's not working because the polyfill being loaded there doesn't have the code for it. Just to be clear, right now you'd need to build master yourself to try it out. 

If `on-demand` is working, you should be able to inspect on the console that  `ShadyDOM.patchOnDemand` is set to `true`.

**Comment by sschottler** [comment]
> @sschottler For your test of `noPatch = on-demand`, it's not working because the polyfill being loaded there doesn't have the code for it. Just to be clear, right now you'd need to build master yourself to try it out.

Ah, I see. So 'on-demand' isn't in the bundled sd script yet, but the noPatch flag is. Setting it to 'on-demand' was probably being treated as truthy and that's why I saw the performance gain, but still needed the explicit `ShadyDOM.wrap` call in my test component. I'll build master locally and give it a shot. 

I'll also verify the correct platform polyfills and master build version of shadydom with the added shadyroot change is being used on my speed test and let you know what I find.

**Comment by sschottler** [comment]
Updated with master build and `on-demand` mode now works as expected without `explicit ShadyDOM.wrap` calls for the individual component test:

http://engineering.rallyhealth.com/polyfill-tests/example-elements/ce-sd-nopatch.html

I also added a speed test with the shady root change and minified builds of the non-platform packages from master:

http://engineering.rallyhealth.com/polyfill-tests/add-nodes-test/shadyrootchange.html

If I don't set `noPatch` to `true` or `on-demand`, I'm seeing:

| Test             | Time to add 10,000 nodes |
|------------------|--------------------------|
| No Polyfills     | ~0.7s                      |
| CE, no SD | ~1.6s                      |
| CE & SD           | ~3.3s                      |

I do have some built-in overhead from running virtualbox on a macbook pro running IE11 on a win7 vm instead of directly, so even my "no polyfills" test runs about the same as your test with shadydom alone. So ShadyDOM adds about 1.5-2 seconds on top of CE by itself even with shadyroot change, but subsequent runs don't get longer and longer like they did before. Also, it used to be like 6.5 seconds on the first run before that fix.

I exported my profiler results if that helps. They ran a bit longer because IE11 gets slower with devtools open, so the times won't match the table above, but the relative ratios should be similar:

- [minified profiler results](https://docs.google.com/spreadsheets/d/1NNsW3s8KfRPMUuxBouOmJmNRUGQGAud2dCVY9r7jmCo/edit#gid=725368678)
- [unminified profiler results](https://docs.google.com/spreadsheets/d/12ldNxGXgoNqSM7fbWkrLunFKFKxIqHcd1uou7ukOpPk/edit#gid=1165750990)

**Comment by sschottler** [comment]
> In particular, currently the custom elements polyfill must be loaded before the shadydom polyfill and the web components bundles do not do this. We do hope to fix this issue shortly.

Is this still true or has the ordering been addressed in the bundle polyfill? Just wondering if on-demand mode still requires loading individual packages to ensure ce is loaded before sd or if it's fine to use the bundle?

**Comment by sorvell** [comment]
Yes, the polyfill re-ordering is still required. We still hope to address
this but we encountered some complexities so this may take a bit.

**Comment by sschottler** [comment]
Ok, thanks!

**Comment by sschottler** [comment]
> Yes, the polyfill re-ordering is still required. We still hope to address this but we encountered some complexities so this may take a bit.

I know it could be awhile, but is there an open issue I could track for progress on this? I can create one if needed. 

We have cobbled together our own polyfill bundle that loads ce/sd in correct order so we can use `on-demand` mode, but I would prefer to use the loader or bundle scripts in this repo whenever they are updated. Thanks!

**Comment by sorvell** [comment]
https://github.com/webcomponents/polyfills/issues/237

**Comment by sschottler** [comment]
Thank you!

**Comment by wbern** [comment]
We've started using 'on-demand' in my org now and it is very useful. I hope this can be better documented for others.
