### ISSUE TITLE
Can ShadyDOM on-demand mode be used in production?

### ISSUE THREAD

**Issue by mkay581** [webcomponents/polyfills#248]
We are using ShadyDOM polyfill in `on-demand` mode as suggested in https://github.com/webcomponents/polyfills/issues/215 with much success (despite its caveats). Based on @sorvell's comments in that thread, there is no documentation of it. But we're a little concerned with using this mode in production. Is it safe? Thanks for any additional help you all can provide.

**Comment by sorvell** [comment]
Yes, it should be safe to use in production. We do hope to release some better documentation in the future but I'm not sure when that will land.
