### ISSUE TITLE
Convert Externs.ts in custom elements to a .d.ts file?

### ISSUE THREAD

**Issue by bicknellr** [webcomponents/polyfills#275]
(@dfreedm pointed this out while reviewing https://github.com/webcomponents/polyfills/pull/274)

Externs.ts doesn't contain any actual code, just type declarations, should this be a .d.ts file instead?

cc @rictic

**Comment by rictic** [comment]
We could, there's not really much reason to prefer one over the other IMO. If you're defining a .d.ts file for a .js file then it has to be .d.ts, but otherwise a file with only declarations could be either.
