### ISSUE TITLE
Manual installation of ShadyDom on a site with no web components

### ISSUE THREAD

**Issue by FranckSCTV** [webcomponents/polyfills#276]
Not a bug report but a something I really need to know as soon as possible.
I just want to know how to install ShadyDom  manually ( no npm ) on a site that doesn't use web components.
I can't find any info about this.
Thanks in advance!

**Comment by bicknellr** [comment]
You could use unpkg to quickly get this on a site: https://unpkg.com/@webcomponents/shadydom/shadydom.min.js

It's also available on npm: https://www.npmjs.com/package/@webcomponents/shadydom
And as part of the webcomponentsjs bundles: https://www.npmjs.com/package/@webcomponents/webcomponentsjs
