### ISSUE TITLE
Edge, IE: document.querySelectorAll returns Array instead of NodeList

### ISSUE THREAD

**Issue by ingoe** [webcomponents/polyfills#277]
### Description
On Edge and IE11 when calling document.querySelectorAll an Array instead of a NodeList is returned.

#### Live Demo
https://jsbin.com/kahopuliba/1/edit?html,console,output

#### Steps to Reproduce
Call document.querySelectorAll using Edge or IE11 on any page which uses webcomponents.bundle.js

#### Expected Results
document.querySelectorAll returns a NodeList
#### Actual Results
document.querySelectorAll returns an Array

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [x] IE 11

**Comment by bicknellr** [comment]
This is likely a limitation of Shady DOM but we should at least add a section to the readme about this.
