### ISSUE TITLE
[ShadyCSS] Does this work with vanilla-style Custom Elements?

### ISSUE THREAD

**Issue by trusktr** [webcomponents/polyfills#29]
For example, I don't want to learn extra APIs in order to make scoped ShadowDOM style work. I'd just like to do this:

```js
class MyElement extends HTMLElement {
  constructor() {
    this.root = this.attachShadow({mode: 'closed'})
    this.root = `
      <style> ... encapsulated styles here ...</style>
      <div> ... content here ... </div>
    `
  }
}

customElements.define('my-element', MyElement)
```

and I'd like for that to have encapsulated styling just like it would with regular ShadowDOM. Does it work this way with ShadyCSS? I'm just wondering because the README makes it seem like I have to call ShadyCSS APIs to make the functionality happen, which is obviously not compatible with regular ShadowDOM.

**Comment by azakus** [comment]
@tomalec is correct. I hope to support this kind of behavior when I can get to #31
