### ISSUE TITLE
[URL] URL isn't compatible to the spec: URL#searchParams

### ISSUE THREAD

**Issue by mysticatea** [webcomponents/polyfills#3]
URL in this polyfill doesn't have `searchParams` property: https://url.spec.whatwg.org/#url-class

(PR #26 looks adding it, but it has not been reviewed while a long time.)

**Comment by edwardgalligan** [comment]
**Note:** The PR link was broken when this was transferred from https://github.com/webcomponents/URL

Original PR was https://github.com/webcomponents/URL/pull/26 and this is now ported to https://github.com/webcomponents/polyfills/pull/7
