### ISSUE TITLE
 JavaScript modules how to import html?

### ISSUE THREAD

**Issue by anlexN** [webcomponents/polyfills#327]
your README.md says "Note that HTML Imports are deprecated in favor of JavaScript modules"

**Comment by bicknellr** [comment]
Hi @anlexN, after HTML Imports were dropped from the specs, JavaScript modules are really the only standard option for linking between source files. Polymer and lit-html have switched over to putting HTML inside template literals which are internally used to populate a `<template>` at runtime to convert them to DOM objects.

If you're looking to write HTML and have that interact with the JS module graph, I'd recommend following https://github.com/w3c/webcomponents/issues/645, where this is being considered for standardization.
