### ISSUE TITLE
[ShadyDOM] Possible memory leak related to noPatch mode and wrapping 

### ISSUE THREAD

**Issue by sorvell** [webcomponents/polyfills#341]
### Description

There may be a memory leak in [ShadyDOM.wrap](https://github.com/webcomponents/polyfills/blob/84fdf87f6cf5832a2e77b0082cd753f12935e7c5/packages/shadydom/src/wrapper.js#L269).

Here the key is typically a `node` and the value is an object that keeps a references to the key `node`. This may prevent the memory from being released as expected when there are otherwise no references to the key `node`.

This issue should be verified and if it's confirmed, instead of using a WeakMap, the wrapper can simply be stored on the node itself in the "shadyData."

**Comment by bicknellr** [comment]
I talked with the team that brought this up and they no longer suspect noPatch is related, so I'm going to close. However, they did also mention seeing https://github.com/webcomponents/polyfills/issues/175 in cases without noPatch, which aren't pressing for them, so we might want to consider looking at that one at some point.
