### ISSUE TITLE
npm package not published anymore?

### ISSUE THREAD

**Issue by tirithen** [webcomponents/polyfills#372]
```
$ npm install @webcomponents/webcomponentsjs                    
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@webcomponents%2fwebcomponentsjs - Not found
npm ERR! 404 
npm ERR! 404  '@webcomponents/webcomponentsjs@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-08-06T10_11_53_594Z-debug.log
```

I tried escaping the / but it gets rewritten the same way. 

Also the package npm registry endpoint is no more, gives 404: https://registry.npmjs.org/@webcomponents/webcomponentsjs

Other packages with @org/package works fine (https://registry.npmjs.org/@material/button ect).

**Comment by bevdam** [comment]
Hello, I also seem to be experiencing this issue.

**Comment by tirithen** [comment]
Nevermind, seems related to issues with the npm service. I hope M$/GitHub acquisition will not cause a lot more of these. :/

**Comment by tirithen** [comment]
GitHub might have shipped off all copies of @webcomponents/webcomponentsjs to the Arctic :D
