### ISSUE TITLE
[ShadyCSS] Parse css-mixins and @apply rules in Angular component-level styles

### ISSUE THREAD

**Issue by firstor** [webcomponents/polyfills#39]
I am using Angular 4 and Polymer 2. The problem is that Polymer 2 supports `css-mixins` but Angular doesn't. So I need to parse `css-mixins` and `@apply` rules in Angular component-level styles. When I tried to use `<custom-style>` feature from Polymer 2, the `css-mixins` worked fine but the styles were messed up. `:not(.style-scope)` was appended to all style selectors and elements were decorated with `style-scope` class. I know that's how ShadeCSS emulates ShadowDOM v1 spec. But as I know, Angular also applies different scoping with ShadeCSS, so I only need to handle what Angular missed - `css-mixins` and `@apply` rules. So I am asking if there is any way to parse them only from the styles inside a certain element which can be retrieved like as `document.querySelector()`?

**Comment by azakus** [comment]
The `@apply` functionality is deprecated, and I'm not sure we want to make it work for more use cases. This may be a good candidate for #31 with `::part`
