### ISSUE TITLE
Publish scoped-custom-element-registry

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/polyfills#426]
We need to publish a `0.0.1` release of https://github.com/webcomponents/polyfills/tree/master/packages/scoped-custom-element-registry to npm as `@webcomponents/scoped-custom-element-registry`.

This should not be integrated with `webcomponents.js` as it is a speculative polyfill.

**Comment by bicknellr** [comment]
Dupe of #424 :)
