### ISSUE TITLE
Move webcomponents polyfills to monorepo

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/polyfills#45]
### Goal:
Reduce friction and improve ability to test and release inter-related changes between polyfills.

### Proposal:
Move all webcomponentsjs constituent polyfills to a "monorepo" using [Lerna](https://github.com/lerna/lerna).  

* `polyfills` (new repo)
  * `packages`
    * `custom-elements` (npm: `@webcomponents/custom-elements`)
    * `shadydom` (npm: `@webcomponents/shadydom`)
    * `shadycss` (npm: `@webcomponents/shadycss`)
    * `template` (npm: `@webcomponents/template`)
    * `url` (npm: `@webcomponents/url`)
    * `webcomponentsjs` (npm: `@webcomponents/webcomponentsjs`)
      * `src`
        * `platform` (retire/combine `webcomponents-platform` into here with local shims)
          * `custom-event.js` (local polyfill for `CustomEvent`, previously in `webcomponents-platform`)
          * `es6-misc.js` (local polyfill for `Array.from` & `Object.assign`, previously in `webcomponents-platform`)
          * `baseURI.js` (local polyfill for `Node.prototype.baseURI`)
          * `promise.js` (loads `promise-polyfill` onto global)
          * `symbol.js` (loads `get-own-property-symbols` and fixes up implementation)
          * `unresolved.js` (shim for `:unresolved`, for polymer-legacy compat)
        * `entrypoints`
          * ...
      * `webcomponents-loader.js`
      * `webcomponents-bundle.js` (build artifact)

### Other considerations
* Will need to migrate open issues from individual repos into `polyfills`, ideally with labels(?) to keep the polyfill-issue association
* We would lose open PR's in this process
* Need to decide whether we can archive the old individual repos or not. 
  * Pros: eliminate confusion on where to file issues for the new polyfills
  * Con: any maintenance releases for old polyfill versions that were distributed on bower (V0 & V1) would still need to be done from the individual repos

**Comment by azakus** [comment]
Done!
