### ISSUE TITLE
[scoped-custom-elements-registry] Setting attributes doesnt work as expected when polyfill enabled

### ISSUE THREAD

**Issue by thepassle** [webcomponents/polyfills#483]
### Description

Using `lit-element@2.4.0` and `@open-wc/scoped-elements@1.3.4` we're noticing some unexpected behavior when setting boolean attributes. The following code:

```js
return html`<scope-me ?fooBar=${true}></scope-me>`;
```

**Behavior _without_ loading the polyfill:**
Sets a `foobar` attribute on `<scope-me>` and it also sets the `fooBar` property to `true`

**Behavior _with_ loading the polyfill:**
Sets a `foobar` attribute on `<scope-me>`, but the `fooBar` property is `undefined`

### Example

```js
/**
 * Specific version:
 *
 * @webcomponents/scoped-custom-element-registry@0.0.3
 * @open-wc/scoped-elements@1.3.4
 * lit-element@2.4.0
 */

// Disabling this import will make `ScopeMe` render ✅
import '@webcomponents/scoped-custom-element-registry';

import { LitElement, html } from 'lit-element';
import { ScopedElementsMixin } from '@open-wc/scoped-elements';

class ScopeMe extends LitElement {
  static get properties() {
    return {
      fooBar: { type: Boolean },
    };
  }

  render() {
    return html`hello ${this.fooBar ? '✅' : '❌'}`;
  }
}

class MyEl extends ScopedElementsMixin(LitElement) {
  static get scopedElements() {
    return {
      'scope-me': ScopeMe,
    };
  }

  render() {
    return html`<scope-me ?fooBar=${true}></scope-me>`;
  }
}

customElements.define('my-el', MyEl);

```

[Stackblitz repro](https://stackblitz.com/edit/js-rjfm8m?file=index.js)

### Version
0.0.3

### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE 11

**Comment by LarsDenBakker** [comment]
@kevinpschaaf @justinfagnani I guess browsers lowercase the attribute, I'm not sure if that's done before setAttribute is called or before attributeChangedCallback is called. What do you think would be the best behavior for the polyfill to follow?

**Comment by justinfagnani** [comment]
setAttribute is called from userland, so it may receive mixed case attribute names. attributeChangedCallback is called by the browser and probably only received lower case names. Looks like the patch for setAttribute needs to lowercase the attribute before calling attributeChangedCallback.

**Comment by thepassle** [comment]
> Looks like the patch for setAttribute needs to lowercase the attribute before calling attributeChangedCallback.

That does indeed seem to lead to the expected behavior: https://stackblitz.com/edit/js-mnczsr?file=polyfill.js
![image](https://user-images.githubusercontent.com/17054057/151128152-6eafb06c-603e-406e-bcd7-d61a0247a239.png)
