### ISSUE TITLE
[scoped-custom-element-registry] toggleAttribute polyfill does not retain force argument

### ISSUE THREAD

**Issue by jmcgavin** [webcomponents/polyfills#533]
### Description

When calling `toggleAttribute`, [the polyfill](https://github.com/webcomponents/polyfills/blob/master/packages/scoped-custom-element-registry/src/scoped-custom-element-registry.js#L349) does not retain the [`force` argument](https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute#syntax).

This means that when I call `toggleAttribute('my-attribute', false)`, the attribute is applied when it should not be.

### Example

```js
// Include the scoped-custom-element-registry polyfill

this.renderRoot.querySelector('my-custom-element').toggleAttribute('my-attribute', false)
```

### Steps to reproduce

1. Call `toggleAttribute` on an element
2. Provide `'my-attribute'` as the first argument
3. Provide `false` as the second argument

#### Expected behavior

`my-attribute` should not be applied to the element.

#### Actual behavior

`my-attribute` is applied to the element.

### Version

@webcomponents/scoped-custom-element-registry@0.0.6

### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [x] IE 11

**Comment by bicknellr** [comment]
The fix for this is available in [`v0.0.8`](https://www.npmjs.com/package/@webcomponents/scoped-custom-element-registry/v/0.0.8).
