### ISSUE TITLE
[scoped-custom-element-registry] The polyfill should not conditionally install itself

### ISSUE THREAD

**Issue by justinfagnani** [webcomponents/polyfills#549]
The Scoped Custom Element Registry proposal is not finalized, and does not have a spec, or any native implementations. The current conditional install based on a [shallow feature detection](https://github.com/webcomponents/polyfills/blob/master/packages/scoped-custom-element-registry/src/scoped-custom-element-registry.js#L14) causes an extreme forward-compatibility risk. If a native implementation ships that defined `ShadowRoot.prototype.createElement` but behaves differently from the polyfill, pages with the polyfill deployed could break.

The polyfill should unconditionally install itself to ensure the current behavior until there is a finalized spec and shipping implementations.

**Comment by regevbr** [comment]
I found another case why this is bad - if you enable chrome://flags/#enable-experimental-web-platform-features the polyfill will not be installed, but importNode feature is not implemented by the chrome flag and as such there is no way to add it and things break

artem-sedykh/mini-climate-card/issues/137

**Comment by justinfagnani** [comment]
Fixed by https://github.com/webcomponents/polyfills/pull/581
