### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by ishmeals** [webcomponents/polyfills#588]
Could a security policy be setup so that I can make a report?

**Comment by jackfromeast** [comment]
Hi, Polyfills Maintainers, @aomarks, @bicknellr!

Could we set up a security policy for this repository to support responsible reporting of security issues? I've opened a pull request here: https://github.com/webcomponents/polyfills/pull/589. Please feel free to modify it as you see fit!

Thank you!

**Comment by ishmeals** [comment]
Hello,

This is a notice that if I receive no response within 1 month of the initial request, I will assume this project to be inactive and publicize details of potential vulnerabilities in your product.

**Comment by rictic** [comment]
We've created a security policy in #592, please report any security issues at https://github.com/webcomponents/polyfills/security/advisories/new

**Comment by jackfromeast** [comment]
Thanks, @rictic!
