### ISSUE TITLE
[ShadyDOM] `document.importNode` broken for custom elements with `shadowRoot` created in constructor

### ISSUE THREAD

**Issue by smalluban** [webcomponents/polyfills#76]
### Description

During tests preparation for adding [hybrids](https://github.com/webcomponents/custom-elements-everywhere/pull/256) to [custom-elements-everywhere](https://github.com/webcomponents/custom-elements-everywhere) I've found a bug, which disallow to use properly `document.importNode`. The custom element created for tests uses a constructor to create `shadowRoot` and its content.

#### Live Demo

https://stackblitz.com/edit/shadydom-import-node-bug

#### Steps to Reproduce

1. Create a custom element, which creates `shadowRoot` and set `childNodes` in constructor method.

Then `document.importNode` is broken. In that case, slotted elements are distributed in wrong way, `MutationObserver` returns wrong mutations and events on children elements are not properly propagated.

The worst scenario is when the element has no `<slot>` element in `shadowRoot` and you want to observe light dom children of the element.

#### Expected Results

Live demo (Chrome):

Custom element content renders once, and  `constructor` called once.

<img width="171" alt="Chrome" src="https://user-images.githubusercontent.com/1906677/41276849-cf79de82-6e25-11e8-9f14-b9aaeb6a991a.png">

#### Actual Results

Live demo (Firefox):

Custom element content broken (created twice, with wrong slot distribution), `constructor` called twice (you can see console log).

<img width="145" alt="zrzut ekranu 2018-06-12 o 09 48 13" src="https://user-images.githubusercontent.com/1906677/41276881-e2d97226-6e25-11e8-9a4c-09b2db37c409.png">

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 9 (didn't check)
- [ ] Safari 8 (didn't check)
- [x] IE 11

### Versions
- webcomponents: v2.0.0

**Comment by isochronous** [comment]
Has literally every issue on this tracker been marked as stale? What the heck?
