### ISSUE TITLE
ShadyDOM breaks directive resolution of Angular.js

### ISSUE THREAD

**Issue by justincy** [webcomponents/polyfills#86]
### Description

Directive resolution in Angular.js is broken when using ShadyDOM. Appears to be caused by `Node.childNodes` not being a live list.

Previous discussion: https://github.com/webcomponents/webcomponentsjs/issues/321

Proposed solution: https://github.com/webcomponents/webcomponentsjs/pull/393

The issue still exists. We'd like to see it get fixed.

#### Live Demo

http://plnkr.co/edit/r2GE2x4vTPBZscMTrn2u?p=preview

### Browsers Affected

All browsers are affected when ShadyDOM is enabled so this particularly affects browsers that don't support the ShadowDOM v1 spec.

**Comment by azakus** [comment]
This is a more specific case of #80
