### ISSUE TITLE
[ShadyDOM] element.shadowRoot.append() is broken in Firefox

### ISSUE THREAD

**Issue by TechQuery** [webcomponents/polyfills#88]
### Description
`element.shadowRoot.append( node )` will throw an error as shown below in Firefox:

> TypeError: 'append' called on an object that does not implement interface DocumentFragment

but `element.shadowRoot.appendChild( node )` works fine.

#### Live Demo
https://codepen.io/tech_query/pen/OBjzQr

### Versions
- webcomponents: v2.0.2+

**Comment by azakus** [comment]
Duplicate of #145
