### ISSUE TITLE
[ShadyDOM] Cannot listen for events from unslotted Light DOM children

### ISSUE THREAD

**Issue by tpluscode** [webcomponents/polyfills#95]
### Description

Events dispatched from Light DOM children cannot be handled unless they are distributed in a `slot`.

#### Live Demo

https://stackblitz.com/edit/shady-dom-events-no-slot

#### Steps to Reproduce

1. Create two elements and nest one in the other.
   * Do not add a `<slot>`
1. Have the child dispatch an event
1. Have the parent listen for that event

#### Expected Results
The event should be handled by the parent.

#### Actual Results
In polyfilled browsers the parent element never receives the event.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- webcomponents: v2.2.7

**Comment by tlouisse** [comment]
Will this and/or https://github.com/webcomponents/polyfills/issues/94 be picked up anytime soon?

Right now we have to resort to hacky, verbose and hard to maintain workarounds to make our code compatible with IE. 
Not ideal as a long term solution... 😕

**Comment by justinfagnani** [comment]
I'm not really sure how we would fix this issue. There's no place in the document we can put unslotted children. The workaround is to have a unnamed slot but style the children as display: none - which approximates what I think is the best we could do in the polyfill anyway. cc @sorvell @dfreedm

**Comment by tlouisse** [comment]
So instead of removing the nodes before slots are distributed, set them to `display:none`?
I tried to do this myself indeed in a custom build and it seemed to be non breaking (as in the tests still ran if I'm right).
As far as I can see the consequences, would be a great solution :)

**Comment by justinfagnani** [comment]
I'm sure that option was considered and there's a reason it wasn't implemented that way.

**Comment by tlouisse** [comment]
Ah, too bad then probably...
If it would be a viable solution though, it would also be more compliant with the spec in a sense that `myHostElement.querySelector('my-not-yet-slotted-el')` would also work inbetween attachShadow and the first render within the shadowRoot. 

(and probably after the render as well, in the case `<my-not-yet-slotted-el slot="myslot">` would never have been slotted (say myHostElement.shadowRoot wouldn't contain `<slot name="myslot">`).

But hopefully you or your colleagues can come up with a solution (be it this or another one) that allows us to fire events again in `connectedCallback` 😅

**Comment by bicknellr** [comment]
BTW, I'm planning to make a release that includes #332 on Monday.

**Comment by bicknellr** [comment]
@webcomponents/webcomponentsjs@2.4.4 (https://github.com/webcomponents/polyfills/commit/34a3d9104a8a4a7a2b4db2ce726cc498be6824a1) is released and should include the fix for this issue.
